apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: product-rule
  namespace: default
spec:
  destination:
    name: product
  match:
    source:
      name: istio-ingress
      labels:
        istio: ingress
    request:
      headers:
        uri:
          prefix: /product
  rewrite:
    uri: /productpage
  route:
  - labels:
      app: productpage